### ISSUE TITLE
/usr/bin/env: «node --harmony»: Нет такого файла или каталога

### ISSUE THREAD

**Issue by ignishub** [getblank/Blank#1]
Вот такая вот фигня у происходит :(  Fedora 25, Nodejs - 6.10.3

**Comment by ivahaev** [comment]
Nodejs должна быть версии от 7.0, до неё async/await не поддерживаются.

**Comment by ignishub** [comment]
Обновил все равно не помогает. Та же ошибка. Попробовал напрямую как говорил ваш разработчик, теперь не запускается сервер.

**Comment by ivahaev** [comment]
Покажите лог проблемного запуска.

**Comment by ignishub** [comment]
Я давно делал это. Вот что я посылал раньше:

https://yadi.sk/i/3aEBquVd3L94VA

**Comment by ivahaev** [comment]
На сколько я вижу, тут другая ошибка.
Конкретно сервис **blank-sr** у себя можете запустить с ключом **-v**. Он должен версии вывести.

**Comment by ignishub** [comment]
Да как я и говорил что я напрямую запустил node --harmony.  Как буду на работе попробую запустить и отпишусь

**Comment by ivahaev** [comment]
Ключи `harmony` более не используются.
